EladInon/Controllers/PackgesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EladInon.Data;
using EladInon.Models;
using Microsoft.AspNetCore.Authorization;

namespace EladInon.Controllers
{
    [Authorize]
    public class PackgesController : Controller
    {
        private readonly PhotoContext _context;

        public PackgesController(PhotoContext context)
        {
            _context = context;
        }

        [AllowAnonymous]
        // GET: Packges
        public async Task<IActionResult> Index(string albumTypeFilter,
                                               string albumTypeSearchString,
                                               string priceFilter,
                                               string priceSearchString)
        {
            InitSearchLists();
            VerifyParameters();
            UpdateFilters();
            var filteredpackages = GetFilteredpackages();
            return View(await filteredpackages.ToListAsync());

            IQueryable<Packge> GetFilteredpackages()
            {
                IQueryable<Packge> packages = _context.Packges;
                packages = string.IsNullOrEmpty(priceSearchString) ? packages : packages.Where(p => p.Price.ToString() == priceSearchString);
                packages = string.IsNullOrEmpty(albumTypeSearchString) ? packages : packages.Where(p => p.AlbumType.ToString() == albumTypeSearchString);
                return packages;
            }

            void UpdateFilters()
            {
                ViewData["priceFilter"] = priceSearchString;
                ViewData["albumTypeFilter"] = albumTypeSearchString;
            }

            void InitSearchLists()
            {
                ViewData["AlbumTypes"] = new SelectList(Enum.GetValues(typeof(AlbumType)));
                ViewData["Prices"] = new SelectList(_context.Packges.Select(p=>p.Price).Distinct());
            }

            void VerifyParameters()
            {
                if (albumTypeSearchString == null)
                    albumTypeSearchString = albumTypeFilter;
                if (priceSearchString == null)
                    priceSearchString = priceFilter;
            }
        }

        [AllowAnonymous]
        // GET: Packges/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var packge = await _context.Packges
                .FirstOrDefaultAsync(m => m.ID == id);
            if (packge == null)
            {
                return NotFound();
            }

            return View(packge);
        }

        // GET: Packges/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Packges/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Description,AlbumType,Price")] Packge packge)
        {
            if (ModelState.IsValid)
            {
                _context.Add(packge);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(packge);
        }

        // GET: Packges/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var packge = await _context.Packges.FindAsync(id);
            if (packge == null)
            {
                return NotFound();
            }
            return View(packge);
        }

        // POST: Packges/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, [Bind("ID,Name,Description,AlbumType,Price")] Packge packge)
        {
            if (id != packge.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(packge);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PackgeExists(packge.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(packge);
        }

        // GET: Packges/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var packge = await _context.Packges
                .FirstOrDefaultAsync(m => m.ID == id);
            if (packge == null)
            {
                return NotFound();
            }

            return View(packge);
        }

        // POST: Packges/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var packge = await _context.Packges.FindAsync(id);
            _context.Packges.Remove(packge);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PackgeExists(int? id)
        {
            return _context.Packges.Any(e => e.ID == id);
        }
    }
}

EladInon/Views/Shared/_Layout.cshtml
@using System.Security.Claims

<!DOCTYPE html>
<html dir="@(System.Threading.Thread.CurrentThread.CurrentCulture.TextInfo.IsRightToLeft? "rtl" : "ltr")"
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - התמונות של עידית</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/bootstrap-rtl.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" />
    @RenderSection("Styles", false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">התמונות של עידית</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Pictures" asp-action="Index" asp-route-locationFilter="@ViewData["locationFilter"]" asp-route-albumFilter="@ViewData["albumFilter"]">הצגת תמונות</a></li>
                    <li><a asp-area="" asp-controller="Albums" asp-action="Index">צפה באלבומים</a></li>
                    <li><a asp-area="" asp-controller="Locations" asp-action="Index">הצגת מיקומים</a></li>
                    <li><a asp-area="" asp-controller="Packges" asp-action="Index">הצגת חבילות</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">אודות</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">יצירת קשר</a></li>
                </ul>
                    @if (Context.User.Identity.IsAuthenticated)
                    {
                        <p class="navbar-text navbar-left"> Administrator <a asp-area="" asp-controller="Account" asp-action="Logoff">התנתק</a></p>
                    }
                    else
                    {
                        <p class="navbar-text navbar-left"><a asp-area="" asp-controller="Account" asp-action="Login">
                            <img id="profile-img" src="//ssl.gstatic.com/accounts/ui/avatar_1x.png" width="20" height="20"/>
                        </a></p>

                    }
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Elad&Inon</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>